"""Generate 6 Yukings application-scenario pages."""
import os, sys, json

sys.path.insert(0, "/workspace/html")
from _generate_templates import CSS, ORG, TOPBAR_HEADER, FOOTER_COOKIE

OUT = "/workspace/html"

def page_data():
    return [
        {
            "filename": "highway-road-noise-barriers.html",
            "title": "Highway / Expressway Noise Barriers | Motorway Sound Walls | Yukings Manufacturer",
            "description": "Yukings highway / expressway noise barriers — galvanized steel louvered absorptive panels designed for motorway and interstate traffic noise control. CE / EN 1793 / EN 1794 certified.",
            "keywords": "highway noise barrier, expressway noise barrier, motorway sound barrier, interstate acoustic barrier, highway noise wall, road traffic noise control",
            "breadcrumb_current": "Highway &amp; Expressway Noise Barriers",
            "hero_eyebrow": "Yukings · Highway &amp; Motorway Noise Control",
            "hero_h1": "Highway &amp; <span>expressway</span> noise barriers — absorptive louvered and transparent acoustic panels for motorways, interstates and intercity trunk roads.",
            "hero_lede": "Yukings highway noise barriers are engineered specifically for motorway and interstate traffic noise, combining galvanized steel louvered absorptive panels with transparent polycarbonate windows to keep driver line-of-sight while reducing noise by up to 42 dB. Standard modular construction for rapid installation along long road corridors.",
            "hero_img": "highway-expressway-noise-barrier-motorway-wall",
            "hero_chips": ["Motorway / Interstate", "EN 1793 / 1794 Tested", "Modular Installation", "Transparent Window Compatible", "Up to 42 dB Insertion"],
            "hero_stats": [("25-42 dB", "insertion loss"), ("80-140 mm", "panel depth"), ("2.0-2.5 m", "post bay"), ("25 yr", "design life")],
            "split_img": "absorptive-highway-noise-barrier-polycarbonate-window",
            "split_title": "Absorptive panels + transparent windows for balanced noise control on motorways.",
            "split_para": "The galvanized steel louvered face on Yukings highway noise barriers allows traffic noise to enter the panel, where hydrophobic rock-wool infill converts sound energy into heat. A transparent polycarbonate window section can be integrated at driver eye level to preserve roadside visibility and satisfy traffic-safety requirements for intercity motorways and interstates.",
            "split_list": ["Motorways, interstates and intercity trunk roads", "Ring roads, bypass corridors and urban expressways", "Bridge parapets and elevated highway structures", "Tunnel approaches, toll plazas and highway interchanges"],
            "spec_title": "Highway Noise Barriers — Product Specification",
            "spec_rows": [
                ("Insertion Loss DL", "25 – 42 dB"),
                ("Sound Insulation Rw", "30 – 52 dB"),
                ("Panel Width", "2500 mm standard"),
                ("Panel Height", "500 mm"),
                ("Panel Depth", "80 / 100 / 120 / 140 mm"),
                ("Panel Face", "DX51D+Z galvanized steel or EN AW-5754 aluminum"),
                ("Infill Material", "hydrophobic rock-wool 80-140 kg/m³"),
                ("H-post Column", "H 100×100×6×8 to H 125×125×6.5×9"),
                ("H-post Spacing", "2.0 m or 2.5 m bays"),
                ("Barrier Height", "2.0 – 5.0 m"),
                ("Design Life", "25 years"),
                ("Warranty", "15 years structural"),
                ("Corrosion", "ISO 12944 C3-M"),
                ("Fire Rating", "Class A EN 13501-1"),
                ("Wind Load", "1.2 kN/m²"),
                ("Finish", "hot-dip galvanized + optional RAL powder coat"),
                ("Transparent Window", "8 / 10 / 12 mm polycarbonate"),
            ],
            "feature_section_title": "What makes our Highway Noise Barriers different",
            "feature_section_intro": "From factory galvanizing through acoustic testing and containerized shipping, Yukings controls every stage of the highway noise barrier production chain to deliver consistent, code-compliant noise control panels.",
            "features": [
                ("EN", "EN 1793 / 1794 Tested", "Panels independently tested for airborne sound insulation and structural performance in highway traffic environments."),
                ("GL", "Galvanized Steel + Aluminum", "Hot-dip galvanized DX51D+Z steel face, with EN AW-5754 aluminum alloy option for corrosive coastal motorway sites."),
                ("PC", "Transparent Window", "Integrated 8/10/12 mm polycarbonate window sections at driver eye level to maintain visibility and safety on high-speed roads."),
                ("MD", "Modular Design", "Standard 2.0 m / 2.5 m bay modular construction for rapid installation on long motorway corridors, with replacement panels available."),
                ("DL", "25-Year Design Life", "Designed for a 25-year service life with a 15-year structural warranty on Yukings-manufactured highway barrier panels."),
                ("CR", "Custom Heights &amp; RAL Colors", "Heights from 2.0 to 5.0 m. Custom RAL powder-coat colors, perforation patterns and green-wall integration available."),
                ("IL", "Up to 42 dB Insertion Loss", "Up to 42 dB broadband insertion loss with 140 mm deep absorptive panels using 120 kg/m³ hydrophobic rock-wool."),
                ("QC", "Factory Quality Control", "Every panel inspected and tested before dispatch, with full dossier including CE and ISO test reports on request."),
            ],
            "related_cards": [
                ("railway-noise-barriers-rail.html", "Railway / High-Speed Rail Noise Barriers", "HSR slipstream-resistant hybrid absorptive-reflective panels for high-speed train corridors.", "Railway"),
                ("city-road-noise-barriers.html", "Urban &amp; City Road Noise Barriers", "Shorter-profile visually-friendly absorptive + transparent panels for residential street noise control.", "City"),
                ("bridge-elevated-noise-barriers.html", "Bridge &amp; Elevated Road Noise Barriers", "Lightweight aluminum alloy panels for parapet mounting on viaducts and elevated expressways.", "Bridge"),
                ("industrial-plant-noise-barriers.html", "Industrial Plant &amp; Factory Noise Barriers", "Heavy-duty hybrid absorptive-reflective walls for factory machinery and plant boundary noise.", "Industrial"),
                ("residential-community-noise-barriers.html", "Residential &amp; Community Noise Barriers", "Shorter-profile absorptive + transparent panels for apartments, housing estates, schools and hospitals.", "Community"),
                ("highway-noise-barriers.html", "Highway Noise Barriers — Core Product", "Classic Yukings highway noise barrier combining galvanized steel louvered metal face with mineral wool core.", "Product"),
            ],
            "faqs": [
                ("How much highway traffic noise can a Yukings noise barrier reduce?", "Yukings highway noise barriers can deliver between 25 dB and 42 dB of insertion loss depending on panel depth (80–140 mm) and your project geometry."),
                ("Are Yukings highway noise barriers tested to European standards?", "Yes. Yukings highway noise barriers are tested to EN 1793 (acoustic performance) and EN 1794 (structural / mechanical performance) with CE marking."),
                ("Can I combine absorptive panels with transparent window sections?", "Yes — this is a standard Yukings configuration. Typical highway barriers combine 1.0–2.0 m of absorptive panel at the base with a 1.0–1.5 m transparent polycarbonate window section."),
                ("What is the design life and warranty for your highway barriers?", "Yukings highway noise barriers are designed for a 25-year service life and carry a 15-year structural warranty when installed according to Yukings specifications."),
            ],
            "cta_h2": "Need a highway noise barrier quote for your motorway or interstate project? <span>Contact Yukings</span> today.",
            "cta_para": "Our highway noise barrier specialists will respond to your project inquiry within 24 hours, including technical guidance, acoustic performance modeling and detailed pricing where applicable.",
        },
        {
            "filename": "railway-noise-barriers-rail.html",
            "title": "Railway &amp; High-Speed Rail Noise Barriers | Train Acoustic Barriers | Yukings Manufacturer",
            "description": "Yukings railway &amp; high-speed rail noise barriers — heavy-duty hybrid absorptive-reflective panels designed for HSR slipstream loads. Up to 45 dB insertion loss, 25-year design life.",
            "keywords": "railway noise barrier, high-speed rail sound barrier, train noise barrier, railway acoustic barrier, railway noise wall, HSR noise control",
            "breadcrumb_current": "Railway &amp; High-Speed Rail Noise Barriers",
            "hero_eyebrow": "Yukings · Railway &amp; HSR Noise Control",
            "hero_h1": "Railway &amp; <span>high-speed rail</span> noise barriers — heavy-duty hybrid acoustic panels engineered for high-speed train slipstream loads and up to 45 dB insertion loss.",
            "hero_lede": "Yukings railway noise barriers and high-speed rail (HSR) acoustic barriers are heavy-duty hybrid absorptive-reflective panels engineered to resist the slipstream suction and pressure wave of 250-350 km/h high-speed trains while delivering up to 45 dB insertion loss. Reinforced fastener systems, captive panel clips and anti-vibration EPDM gaskets are standard on all railway barrier projects.",
            "hero_img": "high-speed-railway-noise-barrier-train-acoustic-wall",
            "hero_chips": ["HSR Slipstream Resistant", "Captive Panel Clips", "Up to 45 dB Insertion", "Hybrid Absorptive + Reflective", "Anti-Vibration Gaskets"],
            "hero_stats": [("30-45 dB", "insertion loss"), ("120-200 mm", "panel depth"), ("2.0 m", "HSR bays"), ("25 yr", "design life")],
            "split_img": "railway-noise-barrier-hybrid-slipstream-panel",
            "split_title": "Hybrid absorptive-reflective panels with captive clips for HSR slipstream resistance.",
            "split_para": "Yukings railway noise barriers combine a perforated absorptive face facing the track with a solid reflective back, connected via heavy-gauge steel framing. Captive panel clips securely fasten each panel to the H-post column to resist slipstream suction forces up to 3.0 kN/m² on 350 km/h high-speed rail lines, while anti-vibration EPDM gaskets dampen panel vibration and prevent structural fatigue over the 25-year design life.",
            "split_list": ["High-speed rail (HSR) lines 250-350 km/h", "Conventional railway corridors and freight lines", "Urban light-rail and metro trackside noise", "Train stations, depots and yard boundary noise"],
            "spec_title": "Railway &amp; HSR Noise Barriers — Product Specification",
            "spec_rows": [
                ("Insertion Loss DL", "30 – 45 dB"),
                ("Sound Insulation Rw", "38 – 55 dB"),
                ("Panel Width", "2000 mm (HSR) / 2500 mm (conventional)"),
                ("Panel Height", "500 mm"),
                ("Panel Depth", "120 / 140 / 160 / 200 mm"),
                ("Face Layer", "perforated / louvered galvanized steel"),
                ("Absorptive Core", "rock-wool 100-140 kg/m³ with EPDM membrane"),
                ("Reflective Back", "2-3 mm solid steel"),
                ("H-post Column", "H 125×125×6.5×9 to H 200×200×9×14"),
                ("H-post Spacing", "2.0 m (HSR) / 2.5 m (conventional)"),
                ("Barrier Height", "3.0 – 8.0 m with cantilever cap option"),
                ("Fastener System", "captive panel clips + anti-vibration EPDM gaskets"),
                ("Aerodynamic Profile", "optional rounded top or cantilever cap to minimize slipstream"),
                ("Design Service Life", "25 years"),
                ("Warranty", "15 years structural"),
                ("Corrosion", "ISO 12944 C4-H"),
                ("Fire Rating", "Class A EN 13501-1"),
                ("Wind / Slipstream Load", "1.5 – 3.0 kN/m² project specified"),
                ("Finish", "hot-dip galvanized + optional RAL powder coat"),
            ],
            "feature_section_title": "Why Yukings Railway Noise Barriers",
            "feature_section_intro": "Heavy-duty construction, captive fastener systems and HSR slipstream testing set Yukings railway noise barriers apart from conventional highway barriers for high-speed rail and railway projects.",
            "features": [
                ("HS", "HSR Slipstream Resistant", "Panels tested to resist slipstream suction and pressure wave from 250-350 km/h high-speed trains with captive panel clips."),
                ("CA", "Captive Fastener System", "Captive panel clips securely lock each panel to the H-post column, preventing dislodgment under high-speed rail slipstream."),
                ("HY", "Hybrid Absorptive-Reflective", "Perforated absorptive face facing the track with a solid reflective back to direct noise upward and away from trackside receivers."),
                ("EV", "Anti-Vibration EPDM Gaskets", "EPDM gaskets between each panel and the H-post column dampen structural vibration and prevent fatigue over 25 years of service."),
                ("IL", "Up to 45 dB Insertion Loss", "120-200 mm deep panels with 100-140 kg/m³ rock-wool core deliver up to 45 dB broadband insertion loss along HSR corridors."),
                ("HE", "Custom Heights to 8.0 m", "Barrier heights from 3.0 m up to 8.0 m, with optional cantilever top cap or rounded aerodynamic cap for HSR lines."),
                ("CO", "C4-H Corrosion Protection", "ISO 12944 C4-H heavy industrial corrosion protection for railway barriers in coastal and industrial environments."),
                ("EN", "EN 1793 / 1794 Tested", "Panels independently tested to EN 1793 acoustic and EN 1794 structural standards with full test reports available."),
            ],
            "related_cards": [
                ("highway-road-noise-barriers.html", "Highway / Expressway Noise Barriers", "Galvanized steel louvered absorptive panels for motorway and interstate traffic noise control.", "Highway"),
                ("city-road-noise-barriers.html", "Urban &amp; City Road Noise Barriers", "Shorter-profile visually-friendly absorptive + transparent panels for residential street and ring road noise.", "City"),
                ("bridge-elevated-noise-barriers.html", "Bridge &amp; Elevated Road Noise Barriers", "Lightweight aluminum alloy panels for parapet mounting on viaducts and elevated expressways.", "Bridge"),
                ("hybrid-noise-barriers.html", "Hybrid Noise Barriers", "Combined absorptive-reflective barrier designs for complex mixed-traffic noise environments.", "Hybrid"),
                ("railway-noise-reduction.html", "Railway Noise Reduction", "Railway noise reduction solutions and project guidance from the Yukings engineering team.", "Solutions"),
                ("railway-noise-barriers.html", "Railway Noise Barriers — Core Product", "Core Yukings railway noise barrier product line with galvanized steel face and mineral wool core.", "Product"),
            ],
            "faqs": [
                ("What is the difference between a railway noise barrier and a highway noise barrier?", "Railway noise barriers use heavier panel construction, captive fastener systems and anti-vibration gaskets to resist the slipstream suction and pressure wave of 250-350 km/h high-speed trains. Highway barriers are optimized for road traffic loads."),
                ("How much noise can a Yukings railway noise barrier reduce?", "Yukings railway noise barriers deliver 30 dB to 45 dB of broadband insertion loss depending on panel depth (120-200 mm) and your specific track geometry and receiver location."),
                ("What is the maximum practical height for a railway noise barrier?", "Yukings designs railway noise barriers from 3.0 m up to 8.0 m in height, with optional cantilever caps or rounded aerodynamic tops to minimize slipstream-induced vibration on HSR lines."),
                ("How are Yukings railway noise barriers fastened to the support columns?", "Yukings railway noise barriers use captive panel clips that securely lock each panel to the H-post column, combined with anti-vibration EPDM gaskets to prevent structural fatigue."),
            ],
            "cta_h2": "Specifying a railway or high-speed rail noise barrier project? <span>Contact Yukings</span> engineering today.",
            "cta_para": "Our railway noise barrier engineers will respond to your project inquiry within 24 hours, including slipstream-load guidance, fastener-system recommendations and detailed project pricing.",
        },
        {
            "filename": "city-road-noise-barriers.html",
            "title": "Urban / City Road Noise Barriers | Residential Street Sound Walls | Yukings Manufacturer",
            "description": "Yukings urban road noise barriers — shorter-profile, visually-friendly absorptive + transparent panels for city streets, ring roads and residential roadside noise control. Custom color and green-wall integration.",
            "keywords": "urban road noise barrier, city road sound barrier, residential street noise barrier, urban acoustic barrier, urban traffic noise wall, green wall noise barrier",
            "breadcrumb_current": "Urban &amp; City Road Noise Barriers",
            "hero_eyebrow": "Yukings · Urban &amp; City Road Noise Control",
            "hero_h1": "Urban &amp; <span>city road</span> noise barriers — shorter-profile visually-friendly absorptive + transparent panels for residential street and ring road noise control.",
            "hero_lede": "Yukings urban road noise barriers are designed for city streets where shorter profile heights, visual friendliness and residential aesthetics are important. Typical configurations combine 1.5-3.0 m absorptive panels at the base with 1.0-2.0 m transparent polycarbonate windows at the top, optionally with green-wall / vertical-garden panel integration or custom RAL color matching to blend with surrounding architecture.",
            "hero_img": "urban-city-road-noise-barrier-residential-street-green-wall",
            "hero_chips": ["Shorter Profile 1.5-3.0 m", "Visually Friendly Design", "Green-Wall Integration Ready", "Custom RAL Color Matching", "Residential Friendly"],
            "hero_stats": [("18-32 dB", "insertion loss"), ("80-120 mm", "panel depth"), ("2.0-2.5 m", "post bay"), ("25 yr", "design life")],
            "split_img": "city-traffic-noise-barrier-transparent-polycarbonate-window",
            "split_title": "Visually friendly absorptive + transparent barrier panels tailored for city streets.",
            "split_para": "Urban environments demand noise control that balances acoustic performance with visual appeal. Yukings city road barriers combine a shorter absorptive panel base with an upper transparent window section to maintain light and visibility, while optional green-wall vertical garden panels integrate planters and vegetation along the roadside for a softer residential aesthetic. Custom RAL color matching is available for any project.",
            "split_list": ["City streets and urban arterial roads", "Ring roads, bypasses and urban roundabouts", "Residential roadside, schools and hospital setbacks", "Retail, commercial and mixed-use urban developments"],
            "spec_title": "Urban &amp; City Road Noise Barriers — Product Specification",
            "spec_rows": [
                ("Insertion Loss DL", "18 – 32 dB"),
                ("Sound Insulation Rw", "25 – 40 dB"),
                ("Panel Width", "2000 / 2500 mm"),
                ("Panel Height", "500 mm"),
                ("Panel Depth", "80 / 100 / 120 mm"),
                ("Panel Face", "galvanized steel / aluminum alloy perforated"),
                ("Infill", "hydrophobic rock-wool 80-120 kg/m³"),
                ("Transparent Top", "8 / 10 / 12 mm polycarbonate or cast acrylic"),
                ("H-post", "H 100×100×6×8"),
                ("H-post Spacing", "2.0 m or 2.5 m bays"),
                ("Barrier Height", "1.5 – 3.5 m"),
                ("Green-Wall Option", "vertical garden panel integration"),
                ("Color", "custom RAL powder coat"),
                ("Finish", "hot-dip galvanized + RAL powder coat"),
                ("Design Service Life", "25 years"),
                ("Structural Warranty", "15 years"),
                ("Fire Rating", "Class A EN 13501-1"),
                ("Wind Load", "1.0 kN/m²"),
            ],
            "feature_section_title": "Why Yukings City Road Noise Barriers",
            "feature_section_intro": "Engineered for urban visual appeal as well as acoustic performance, Yukings city road barriers deliver residential-friendly noise control without compromising style.",
            "features": [
                ("SP", "Shorter Profile Heights", "1.5–3.5 m barrier heights optimized for city streets, residential setbacks and low-rise urban environments."),
                ("VF", "Visually Friendly Design", "Smooth powder-coat finishes with custom RAL colors to match surrounding architecture and urban design guidelines."),
                ("TW", "Transparent Window Top", "8 / 10 / 12 mm polycarbonate or cast acrylic window at the top of the barrier preserves light and visibility for residents."),
                ("GW", "Green-Wall Ready", "Vertical garden panel integration option with planter sections that support live vegetation along the barrier."),
                ("CR", "Custom RAL Color Matching", "Full RAL color palette available for powder-coat finish to match architectural requirements in sensitive urban zones."),
                ("RF", "Residential Friendly", "Designed for apartment buildings, housing estates, schools and hospitals where a softer visual profile is essential."),
                ("IL", "18-32 dB Insertion Loss", "Balanced broadband insertion loss from 80-120 mm deep panels for typical urban traffic noise reduction targets."),
                ("EN", "EN 1793 / 1794 Tested", "Panels independently tested to EN 1793 and EN 1794 for acoustic and structural performance in urban environments."),
            ],
            "related_cards": [
                ("residential-community-noise-barriers.html", "Residential &amp; Community Noise Barriers", "Shorter-profile absorptive + transparent panels for apartments, housing estates, schools and hospitals.", "Community"),
                ("highway-road-noise-barriers.html", "Highway / Expressway Noise Barriers", "Galvanized steel louvered absorptive panels for motorway and interstate traffic noise control.", "Highway"),
                ("transparent-noise-barriers.html", "Transparent Noise Barriers", "Polycarbonate and cast acrylic transparent barrier panels for projects where visibility is a priority.", "Transparent"),
                ("residential-community-noise-protection.html", "Residential Community Noise Protection", "Yukings solutions for residential community noise protection and community-scale acoustic barriers.", "Solutions"),
                ("residential-noise-barriers.html", "Residential Noise Barriers — Core Product", "Core Yukings residential noise barrier product line with absorptive and transparent panel options.", "Product"),
                ("city-road-noise-barriers.html", "Urban &amp; City Road Noise Barriers", "Shorter-profile visually-friendly absorptive + transparent panels for city streets and ring roads.", "City"),
            ],
            "faqs": [
                ("How tall does a city road noise barrier need to be?", "Yukings urban road noise barriers are typically 1.5 to 3.5 m tall depending on traffic speed, volume, distance to the receiver and the specific noise reduction target of your project."),
                ("Can I match the barrier color to my city street furniture?", "Yes — Yukings offers full custom RAL powder-coat color matching on all city road noise barriers to blend with surrounding architecture, street furniture and public design standards."),
                ("Are green-wall or vertical garden barrier options available?", "Yes. Yukings city road noise barriers can integrate vertical garden / green-wall panel sections with planter boxes to support vegetation along the roadside barrier."),
                ("Do your urban barriers use transparent window sections?", "Yes. Typical urban barrier configurations combine a lower 1.5–3.0 m absorptive panel section with an upper 1.0–2.0 m transparent polycarbonate or cast acrylic window at the top."),
            ],
            "cta_h2": "Planning an urban street or ring road noise barrier project? <span>Ask Yukings</span> for a tailored design.",
            "cta_para": "Our urban noise barrier design team will respond within 24 hours with guidance on barrier height, visual-finish options, green-wall integration and detailed project pricing.",
        },
        {
            "filename": "bridge-elevated-noise-barriers.html",
            "title": "Bridge &amp; Elevated Road Noise Barriers | Viaduct Sound Barriers | Yukings Manufacturer",
            "description": "Yukings bridge &amp; elevated road noise barriers — lightweight aluminum alloy or thin-profile composite panels for parapet mounting on viaducts, overpasses and elevated expressways.",
            "keywords": "bridge noise barrier, overpass sound barrier, elevated road acoustic barrier, bridge parapet noise wall, viaduct noise barrier, aluminum noise barrier",
            "breadcrumb_current": "Bridge &amp; Elevated Road Noise Barriers",
            "hero_eyebrow": "Yukings · Bridge &amp; Viaduct Noise Control",
            "hero_h1": "Bridge &amp; <span>elevated road</span> noise barriers — lightweight aluminum alloy panels for parapet mounting on viaducts, overpasses and elevated expressways.",
            "hero_lede": "Yukings bridge noise barriers are specifically designed for parapet mounting on viaducts, overpasses and elevated expressway structures. Using lightweight EN AW-5754 aluminum alloy panels minimizes the structural dead-load on the bridge deck while maintaining full acoustic performance. Specialized bracket systems ensure secure attachment to existing concrete or steel parapets without structural modification.",
            "hero_img": "bridge-elevated-road-noise-barrier-viaduct-parapet",
            "hero_chips": ["Lightweight Aluminum Alloy", "Parapet Mounted Bracket", "Dead-Load Optimized", "Viaduct &amp; Overpass Ready", "Transparent Window Compatible"],
            "hero_stats": [("20-32 dB", "insertion loss"), ("80-120 mm", "panel depth"), ("2.0 m", "bracket bay"), ("25 yr", "design life")],
            "split_img": "aluminum-lightweight-bridge-parapet-noise-barrier",
            "split_title": "Lightweight aluminum alloy panels with custom parapet-mounted brackets for viaducts and overpasses.",
            "split_para": "Yukings bridge noise barriers use thin-gauge EN AW-5754 aluminum alloy panels with hydrophobic rock-wool infill to keep unit weight as low as possible — a critical factor when adding noise barriers to an existing bridge deck. Custom hot-dip galvanized steel brackets are designed to bolt directly to existing concrete or steel parapets without modifying the bridge structure or requiring new foundation work. Transparent polycarbonate window sections can be integrated to preserve driver visibility on viaducts.",
            "split_list": ["Viaducts and elevated expressway structures", "Overpasses, flyovers and ramp parapets", "Bridge decks on intercity and coastal bridges", "Canal, river and railway-crossing bridge parapets"],
            "spec_title": "Bridge &amp; Elevated Road Noise Barriers — Product Specification",
            "spec_rows": [
                ("Insertion Loss DL", "20 – 32 dB"),
                ("Sound Insulation Rw", "24 – 38 dB"),
                ("Panel Material", "EN AW-5754 aluminum alloy 1.5–2.0 mm"),
                ("Panel Width", "2000 mm"),
                ("Panel Height", "500 mm"),
                ("Panel Depth", "80 / 100 / 120 mm"),
                ("Infill", "hydrophobic rock-wool 80-120 kg/m³"),
                ("Transparent Window", "8 / 10 / 12 mm polycarbonate compatible"),
                ("Parapet Bracket", "custom hot-dip galvanized steel bolted to existing parapet"),
                ("H-post / Bracket", "aluminum alloy H or steel H 100×100×6×8"),
                ("Bracket Spacing", "2.0 m bays"),
                ("Barrier Height", "2.0 – 4.0 m"),
                ("Panel Unit Weight", "12-22 kg/m² optimized for bridge dead-load"),
                ("Corrosion", "C5-M marine grade"),
                ("Fire Rating", "Class A EN 13501-1"),
                ("Wind Load", "1.2 kN/m²"),
                ("Finish", "anodized or PVDF powder coat"),
                ("Design Service Life", "25 years"),
                ("Structural Warranty", "15 years"),
            ],
            "feature_section_title": "What makes our Bridge Noise Barriers different",
            "feature_section_intro": "Lightweight aluminum alloy construction, custom parapet-mounted brackets and marine-grade corrosion protection set Yukings bridge noise barriers apart from conventional highway panels for elevated road projects.",
            "features": [
                ("AL", "Lightweight Aluminum Alloy", "EN AW-5754 aluminum alloy panels at just 12-22 kg/m² minimize added dead-load on existing bridge decks."),
                ("PB", "Parapet-Mounted Brackets", "Custom hot-dip galvanized steel brackets bolt directly to existing concrete or steel parapets without structural modification."),
                ("DL", "Dead-Load Optimized", "Barrier system fully weight-optimized for retrofit installation on existing bridges with limited reserve capacity."),
                ("VI", "Viaduct &amp; Overpass Ready", "Complete design support for viaducts, overpasses, flyovers and ramp parapets on elevated expressway projects."),
                ("TW", "Transparent Window Compatible", "8 / 10 / 12 mm polycarbonate transparent window sections can be integrated at driver eye level to preserve visibility."),
                ("C5", "C5-M Marine Corrosion", "C5-M marine-grade corrosion protection standard on all bridge barrier projects in coastal or de-icing salt environments."),
                ("AN", "Anodized or PVDF Finish", "Anodized or PVDF powder-coat finish options for long-term color stability and UV resistance in exterior bridge installations."),
                ("EN", "EN 1793 / 1794 Tested", "Panels independently tested to EN 1793 acoustic and EN 1794 structural standards with full project dossiers available."),
            ],
            "related_cards": [
                ("aluminum-noise-barriers.html", "Aluminum Noise Barriers", "Lightweight EN AW-5754 aluminum alloy noise barrier panels for weight-sensitive projects and environments.", "Aluminum"),
                ("highway-road-noise-barriers.html", "Highway / Expressway Noise Barriers", "Galvanized steel louvered absorptive panels for motorway and interstate traffic noise control.", "Highway"),
                ("transparent-noise-barriers.html", "Transparent Noise Barriers", "Polycarbonate and cast acrylic transparent barrier panels for projects where visibility is a priority.", "Transparent"),
                ("city-road-noise-barriers.html", "Urban &amp; City Road Noise Barriers", "Shorter-profile visually-friendly absorptive + transparent panels for city streets and ring roads.", "City"),
                ("highway-noise-control.html", "Highway Noise Control", "Yukings highway noise control solutions for large-scale expressway and road corridor projects.", "Solutions"),
                ("bridge-elevated-noise-barriers.html", "Bridge &amp; Elevated Road Noise Barriers", "Lightweight aluminum alloy panels for parapet mounting on viaducts, overpasses and elevated expressways.", "Bridge"),
            ],
            "faqs": [
                ("How much do bridge noise barriers weigh per square meter?", "Yukings bridge noise barriers using EN AW-5754 aluminum alloy panels weigh only 12-22 kg/m² depending on panel depth, minimizing added dead-load on the bridge deck."),
                ("Can bridge noise barriers be retrofitted to an existing bridge?", "Yes. Yukings provides custom hot-dip galvanized steel brackets that bolt directly to existing concrete or steel parapets without modifying the bridge structure or adding new foundations."),
                ("What corrosion protection do you provide for coastal bridge barriers?", "Yukings bridge noise barriers are supplied with C5-M marine-grade corrosion protection and either anodized or PVDF powder-coat finish for coastal and de-icing-salt environments."),
                ("Can I have transparent window sections on my bridge noise barrier?", "Yes — transparent 8/10/12 mm polycarbonate window sections can be integrated into Yukings bridge noise barriers to preserve driver visibility on viaducts and overpasses."),
            ],
            "cta_h2": "Designing a bridge or viaduct noise barrier retrofit project? <span>Consult Yukings</span> engineering today.",
            "cta_para": "Our bridge noise barrier specialists will respond within 24 hours with guidance on bracket systems, dead-load assessment, parapet integration and detailed project pricing.",
        },
        {
            "filename": "industrial-plant-noise-barriers.html",
            "title": "Industrial Plant &amp; Factory Noise Barriers | Machinery Noise Control Walls | Yukings Manufacturer",
            "description": "Yukings industrial plant noise barriers — heavy-duty absorptive + reflective hybrid walls for factory machinery, cooling towers, compressor stations and plant boundary noise control. Up to 45 dB insertion loss.",
            "keywords": "industrial noise barrier, factory sound barrier, plant noise control wall, industrial acoustic barrier, machinery noise enclosure barrier, cooling tower noise wall",
            "breadcrumb_current": "Industrial Plant &amp; Factory Noise Barriers",
            "hero_eyebrow": "Yukings · Industrial &amp; Factory Noise Control",
            "hero_h1": "Industrial <span>plant &amp; factory</span> noise barriers — heavy-duty absorptive-reflective hybrid walls for machinery noise, cooling towers, compressor stations and plant boundary noise control.",
            "hero_lede": "Yukings industrial plant noise barriers are heavy-duty hybrid absorptive-reflective walls engineered for factory machinery noise, cooling towers, compressor stations, generator sets, crushers and plant boundary noise control. Deep 120-200 mm panels with double-layer steel and rock-wool core deliver up to 45 dB broadband insertion loss, with C4-H heavy corrosion protection for chemical / coastal industrial environments.",
            "hero_img": "industrial-plant-factory-noise-barrier-machinery-noise-control",
            "hero_chips": ["Heavy-Duty Hybrid", "C4-H Corrosion Protection", "Up to 45 dB Insertion", "Machinery / Cooling Tower Ready", "Custom Heights 2-12 m"],
            "hero_stats": [("35-45 dB", "insertion loss"), ("120-200 mm", "panel depth"), ("2.0-2.5 m", "post bay"), ("25 yr", "design life")],
            "split_img": "heavy-industrial-noise-barrier-factory-boundary-wall",
            "split_title": "Heavy-duty hybrid absorptive-reflective walls for factory, plant and machinery noise sources.",
            "split_para": "Yukings industrial noise barriers use a double-layer construction: a perforated absorptive face facing the noise source (machinery, cooling tower, compressor station) backed by a solid galvanized steel reflective plate to prevent sound transmission through the barrier. Panels are 120 to 200 mm deep with 100-140 kg/m³ rock-wool infill protected by an EPDM membrane for industrial dust and water resistance. Barrier heights range from 3.0 to 12.0 m with optional cantilever caps for extended plant boundary noise reduction.",
            "split_list": ["Factory machinery, presses and crusher noise", "Cooling towers, chiller plants and HVAC equipment", "Compressor stations, generator sets and pumps", "Plant boundary / perimeter noise control and zoning compliance"],
            "spec_title": "Industrial Plant Noise Barriers — Product Specification",
            "spec_rows": [
                ("Insertion Loss DL", "35 – 45 dB"),
                ("Sound Insulation Rw", "42 – 58 dB"),
                ("Panel Material", "DX51D+Z galvanized steel 1.5–3.0 mm"),
                ("Panel Width", "2500 mm"),
                ("Panel Height", "500 mm"),
                ("Panel Depth", "120 / 140 / 160 / 200 mm"),
                ("Absorptive Core", "rock-wool 100-140 kg/m³ with EPDM membrane"),
                ("Reflective Back", "solid galvanized steel"),
                ("H-post Column", "H 125×125×6.5×9 to H 200×200×9×14"),
                ("H-post Spacing", "2.0 m or 2.5 m bays"),
                ("Barrier Height", "3.0 – 12.0 m with cantilever cap / fan-shield top"),
                ("Corrosion", "ISO 12944 C4-H heavy industrial"),
                ("Fire Rating", "Class A EN 13501-1"),
                ("Wind / Blast Load", "1.5 kN/m² (higher on project request)"),
                ("Weathering", "UV and chemical resistant finish"),
                ("Finish", "hot-dip galvanized + RAL powder coat"),
                ("Acoustic Door / Access Panel", "factory-matched acoustic door"),
                ("Design Service Life", "25 years"),
                ("Structural Warranty", "15 years"),
            ],
            "feature_section_title": "Why Yukings Industrial Noise Barriers",
            "feature_section_intro": "Heavy-duty construction, industrial-grade corrosion protection and project-specific acoustic design make Yukings industrial noise barriers a robust choice for factory and plant noise control projects.",
            "features": [
                ("HD", "Heavy-Duty Hybrid", "Double-layer steel construction with absorptive face facing the noise source and a solid reflective back for maximum insertion loss."),
                ("C4", "C4-H Corrosion Protection", "ISO 12944 C4-H heavy industrial corrosion protection standard on all industrial barrier panels for chemical and coastal environments."),
                ("IL", "Up to 45 dB Insertion Loss", "120-200 mm deep panels with 100-140 kg/m³ rock-wool core deliver up to 45 dB broadband insertion loss on industrial sites."),
                ("CT", "Cooling Tower &amp; Machinery Ready", "Panels engineered for close-in installation around cooling towers, compressors, generator sets, crushers and factory machinery."),
                ("CH", "Custom Heights to 12.0 m", "Barrier heights from 3.0 m up to 12.0 m with optional cantilever caps or fan-shield tops for tall plant boundary applications."),
                ("AC", "Acoustic Access Door", "Factory-matched acoustic access doors and personnel panels to maintain barrier performance at plant entry points."),
                ("FR", "Class A Fire Rating", "EN 13501-1 Class A fire rating on all Yukings industrial noise barrier panels for industrial building compliance."),
                ("EN", "EN 1793 / 1794 Tested", "Panels independently tested to EN 1793 (acoustic) and EN 1794 (structural) standards with full project test dossiers."),
            ],
            "related_cards": [
                ("reflective-noise-barriers.html", "Reflective Noise Barriers", "Solid reflective noise barrier designs using heavy-gauge galvanized steel for maximum transmission loss.", "Reflective"),
                ("hybrid-noise-barriers.html", "Hybrid Noise Barriers", "Combined absorptive-reflective hybrid barrier designs for complex industrial and mixed-traffic noise environments.", "Hybrid"),
                ("highway-road-noise-barriers.html", "Highway / Expressway Noise Barriers", "Galvanized steel louvered absorptive panels for motorway and interstate traffic noise control.", "Highway"),
                ("industrial-noise-barriers.html", "Industrial Noise Barriers — Core Product", "Core Yukings industrial noise barrier product line with heavy-gauge steel and rock-wool core.", "Product"),
                ("industrial-factory-noise-barriers.html", "Industrial Factory Noise Barriers", "Yukings complete industrial and factory noise barrier solutions from the solutions and projects library.", "Solutions"),
                ("industrial-plant-noise-barriers.html", "Industrial Plant Noise Barriers", "Heavy-duty hybrid absorptive-reflective walls for machinery, cooling towers and plant boundary noise control.", "Industrial"),
            ],
            "faqs": [
                ("How much noise can an industrial noise barrier reduce?", "Yukings industrial noise barriers deliver 35 dB to 45 dB broadband insertion loss depending on panel depth (120-200 mm), barrier height and your specific source-receiver geometry."),
                ("Can industrial noise barriers be used around cooling towers?", "Yes. Yukings industrial noise barriers are routinely used around cooling towers, chiller plants, compressor stations, generator sets and crushers to reduce plant boundary noise to zoning-compliant levels."),
                ("What corrosion protection is provided for chemical and coastal industrial environments?", "Yukings industrial noise barriers are supplied with ISO 12944 C4-H heavy industrial corrosion protection with hot-dip galvanized steel and optional RAL powder-coat finish for chemical and coastal plant environments."),
                ("Can acoustic access doors be integrated into the barrier?", "Yes. Yukings provides factory-matched acoustic access doors and personnel panels at any required location in the barrier to maintain acoustic performance at plant entry points."),
            ],
            "cta_h2": "Controlling factory or plant boundary noise to meet zoning requirements? <span>Ask Yukings</span> for an industrial barrier design.",
            "cta_para": "Our industrial noise control engineers will respond to your project inquiry within 24 hours with guidance on barrier height, source-specific panel selection, corrosion protection and detailed project pricing.",
        },
        {
            "filename": "residential-community-noise-barriers.html",
            "title": "Residential &amp; Community Noise Barriers | Neighborhood Acoustic Fences | Yukings Manufacturer",
            "description": "Yukings residential &amp; community noise barriers — shorter-profile absorptive + transparent panels for apartments, housing estates, schools and hospital roadside noise reduction. Custom color and green-wall integration.",
            "keywords": "residential noise barrier, community sound barrier, residential acoustic fence, neighborhood noise wall, backyard noise barrier, school hospital noise reduction",
            "breadcrumb_current": "Residential &amp; Community Noise Barriers",
            "hero_eyebrow": "Yukings · Residential &amp; Community Noise Control",
            "hero_h1": "Residential &amp; <span>community</span> noise barriers — shorter-profile absorptive + transparent panels for apartments, housing estates, schools and hospitals near road traffic.",
            "hero_lede": "Yukings residential noise barriers are designed to reduce road traffic and railway noise reaching apartment buildings, housing estates, schools, hospitals and community spaces. Typical configurations combine lower absorptive panels with upper transparent polycarbonate windows to maintain visual openness and natural light. Custom RAL colors and green-wall vertical garden integration help the barrier blend with surrounding residential architecture.",
            "hero_img": "residential-community-noise-barrier-apartment-housing-estate",
            "hero_chips": ["Apartment / Housing Estate", "School / Hospital Friendly", "Visual Openness with Transparent Windows", "Custom RAL Color Matching", "Green-Wall Vertical Garden Integration"],
            "hero_stats": [("18-30 dB", "insertion loss"), ("80-120 mm", "panel depth"), ("2.0-2.5 m", "post bay"), ("25 yr", "design life")],
            "split_img": "neighborhood-acoustic-fence-transparent-window-residential",
            "split_title": "Visually open absorptive + transparent residential acoustic panels tailored for community environments.",
            "split_para": "Residential communities need noise control that protects living spaces without creating a walled-in feeling. Yukings residential noise barriers combine a lower absorptive panel section with an upper transparent polycarbonate or cast acrylic window to preserve natural light and visual openness, while custom RAL colors, wood-grain or stone-effect film finishes and green-wall vertical garden integration help the barrier blend smoothly into residential architecture.",
            "split_list": ["Apartment buildings and multi-story housing estates", "Schools, universities and childcare facilities", "Hospitals, clinics and healthcare campuses", "Community parks, playgrounds and public recreation areas"],
            "spec_title": "Residential &amp; Community Noise Barriers — Product Specification",
            "spec_rows": [
                ("Insertion Loss DL", "18 – 30 dB"),
                ("Sound Insulation Rw", "22 – 38 dB"),
                ("Panel Material", "DX51D+Z galvanized steel or EN AW-5754 aluminum"),
                ("Panel Width", "2000 / 2500 mm"),
                ("Panel Height", "500 mm"),
                ("Panel Depth", "80 / 100 / 120 mm"),
                ("Absorptive Core", "rock-wool 80-120 kg/m³"),
                ("Transparent Window", "8 / 10 / 12 mm polycarbonate / cast acrylic"),
                ("Green-Wall Option", "vertical garden panel integration"),
                ("H-post Column", "H 100×100×6×8"),
                ("H-post Spacing", "2.0 m or 2.5 m bays"),
                ("Barrier Height", "1.5 – 3.5 m"),
                ("Color", "custom RAL powder coat with wood-grain / stone-effect film options"),
                ("Finish", "hot-dip galvanized + RAL powder coat"),
                ("Corrosion", "ISO 12944 C3-M"),
                ("Fire Rating", "Class A EN 13501-1"),
                ("Wind Load", "1.0 kN/m²"),
                ("Design Service Life", "25 years"),
                ("Structural Warranty", "15 years"),
            ],
            "feature_section_title": "What makes our Residential Noise Barriers different",
            "feature_section_intro": "Designed to reduce noise while preserving visual openness and residential comfort, Yukings community noise barriers deliver acoustic performance without sacrificing the quality of your living environment.",
            "features": [
                ("AP", "Apartment &amp; Housing Estate", "Barrier systems designed for apartment buildings, housing estates and multi-family residential developments near traffic corridors."),
                ("SH", "School &amp; Hospital Friendly", "Visually soft profiles and low-profile designs suitable for schools, universities, hospitals, clinics and childcare facilities."),
                ("VO", "Visual Openness", "Upper transparent polycarbonate or cast acrylic window sections preserve natural light, sightlines and visual openness for residents."),
                ("CR", "Custom RAL Color Matching", "Full custom RAL powder-coat color matching to blend with surrounding residential architecture and community design guidelines."),
                ("GW", "Green-Wall Vertical Garden", "Optional green-wall vertical garden panel integration with planter boxes to support vegetation along the roadside barrier."),
                ("WS", "Wood-Grain &amp; Stone-Effect", "Optional wood-grain or stone-effect film finishes for a softer visual profile that complements residential landscape design."),
                ("IL", "18-30 dB Insertion Loss", "Balanced broadband insertion loss from 80-120 mm deep panels for typical residential and community road traffic noise targets."),
                ("EN", "EN 1793 / 1794 Tested", "Panels independently tested to EN 1793 and EN 1794 for acoustic and structural performance with full test reports available."),
            ],
            "related_cards": [
                ("city-road-noise-barriers.html", "Urban &amp; City Road Noise Barriers", "Shorter-profile visually-friendly absorptive + transparent panels for city streets and residential ring road noise.", "City"),
                ("highway-road-noise-barriers.html", "Highway / Expressway Noise Barriers", "Galvanized steel louvered absorptive panels for motorway and interstate traffic noise control.", "Highway"),
                ("transparent-noise-barriers.html", "Transparent Noise Barriers", "Polycarbonate and cast acrylic transparent barrier panels for projects where visibility and natural light matter.", "Transparent"),
                ("residential-noise-barriers.html", "Residential Noise Barriers — Core Product", "Core Yukings residential noise barrier product line with absorptive and transparent panel options.", "Product"),
                ("residential-community-noise-protection.html", "Residential Community Noise Protection", "Yukings complete residential community noise protection solutions from our solutions and projects library.", "Solutions"),
                ("residential-community-noise-barriers.html", "Residential &amp; Community Noise Barriers", "Shorter-profile absorptive + transparent panels for apartments, housing estates, schools and hospitals.", "Community"),
            ],
            "faqs": [
                ("How high does a residential noise barrier need to be?", "Yukings residential noise barriers are typically 1.5 to 3.5 m tall depending on traffic volume, speed, distance to your building and the specific noise reduction target of your project."),
                ("Can residential noise barriers preserve natural light and views?", "Yes. Yukings residential noise barriers typically combine a lower absorptive panel section with an upper 8/10/12 mm polycarbonate or cast acrylic transparent window to preserve natural light and visual openness."),
                ("Can I match the barrier color to my community design standards?", "Yes — Yukings offers full custom RAL powder-coat color matching plus optional wood-grain and stone-effect film finishes to blend with surrounding residential architecture."),
                ("Are green-wall or vertical garden residential barrier options available?", "Yes. Yukings residential noise barriers can integrate green-wall vertical garden panel sections with planter boxes to support vegetation and create a softer roadside profile."),
            ],
            "cta_h2": "Reducing traffic noise for your community, school or housing estate? <span>Contact Yukings</span> for a residential barrier design.",
            "cta_para": "Our residential noise barrier design team will respond within 24 hours with guidance on barrier height, visual-finish options, transparent-window configuration and detailed project pricing.",
        },
    ]

def build_page(p):
    def img_url(prompt):
        return f"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt={prompt}&image_size=landscape_16_9"

    chips_html = "".join(
        f'<span class="rsb-hero__chip">{c}</span>' for c in p["hero_chips"]
    )
    stats_html = "".join(
        f'<div class="rsb-hero__stat"><strong>{v}</strong><span>{label}</span></div>'
        for v, label in p["hero_stats"]
    )

    split_list_html = "".join(f"<li>{item}</li>" for item in p["split_list"])

    spec_rows_html = "".join(
        f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in p["spec_rows"]
    )

    features_html = "".join(
        f'<div class="rsb-feature"><i class="rsb-feature__icon">{icon}</i><h3>{title}</h3><p>{body}</p></div>'
        for icon, title, body in p["features"]
    )

    cards_html = "".join(
        f'<div class="rsb-card"><a href="{url}"><div class="rsb-card__media"><div class="rsb-card__img" style="background-image:url(\'{img_url(tag.lower()+"-noise-barrier")}\')"></div><span class="rsb-card__tag">{tag}</span></div><div class="rsb-card__body"><span class="rsb-card__meta">{tag}</span><h3 class="rsb-card__title">{title}</h3><p class="rsb-card__text">{desc}</p><span class="rsb-card__link">View {tag.lower()} barriers &rarr;</span></div></a></div>'
        for url, title, desc, tag in p["related_cards"]
    )

    faq_html = "".join(
        f'<div class="rsb-faq__item"><div class="rsb-faq__q">{q}</div><div class="rsb-faq__a">{a}</div></div>'
        for q, a in p["faqs"]
    )

    crumb_list = f'<li><a href="index.html">Home</a></li><li class="rsb-breadcrumb__sep">/</li><li><a href="solutions.html">Application Scenarios</a></li><li class="rsb-breadcrumb__sep">/</li><li><span class="rsb-breadcrumb__current">{p["breadcrumb_current"]}</span></li>'

    breadcrumb_json = json.dumps({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": "https://www.yukings.net/index.html"},
            {"@type": "ListItem", "position": 2, "name": "Application Scenarios", "item": "https://www.yukings.net/solutions.html"},
            {"@type": "ListItem", "position": 3, "name": p["breadcrumb_current"]},
        ],
    })
    breadcrumb_script = f'<script type="application/ld+json">{breadcrumb_json}</script>'

    html_parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        f"<title>{p['title']}</title>",
        f'<meta name="description" content="{p["description"]}">',
        f'<meta name="keywords" content="{p["keywords"]}">',
        '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">',
        '<meta name="author" content="Shenzhen Yukings Industrial Co., Ltd.">',
        f'<link rel="canonical" href="https://www.yukings.net/{p["filename"]}">',
        f'<link rel="alternate" hreflang="en" href="https://www.yukings.net/{p["filename"]}">',
        f'<link rel="alternate" hreflang="x-default" href="https://www.yukings.net/{p["filename"]}">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:title" content="{p["title"]}">',
        f'<meta property="og:description" content="{p["description"]}">',
        f'<meta property="og:url" content="https://www.yukings.net/{p["filename"]}">',
        '<meta property="og:site_name" content="Yukings - Noise Barrier Manufacturer">',
        f'<meta property="og:image" content="{img_url(p["hero_img"])}">',
        '<meta property="og:locale" content="en_US">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{p["title"]}">',
        f'<meta name="twitter:description" content="{p["description"]}">',
        f'<meta name="twitter:image" content="{img_url(p["hero_img"])}">',
        CSS,
        ORG,
        breadcrumb_script,
        "</head>",
        "<body>",
        TOPBAR_HEADER,
        '<nav class="rsb-breadcrumb"><div class="rsb-container"><ol class="rsb-breadcrumb__list">',
        crumb_list,
        "</ol></div></nav>",
        '<section class="rsb-hero">',
        f'<div class="rsb-hero__bg" style="background-image:url(\'{img_url(p["hero_img"])}\')"></div>',
        '<div class="rsb-container"><div class="rsb-hero__content">',
        f'<span class="rsb-hero__eyebrow">{p["hero_eyebrow"]}</span>',
        f'<h1>{p["hero_h1"]}</h1>',
        f'<p class="lede">{p["hero_lede"]}</p>',
        '<div class="rsb-hero__actions"><a href="get-quote.html" class="rsb-btn rsb-btn--primary rsb-btn--lg">Request a Free Quote</a><a href="products.html" class="rsb-btn rsb-btn--ghost rsb-btn--lg">Browse Our Products</a></div>',
        f'<div class="rsb-hero__quick">{chips_html}</div>',
        f'<div class="rsb-hero__stats">{stats_html}</div>',
        "</div></div></section>",
        # Split / overview section
        '<section class="rsb-section rsb-section--gray"><div class="rsb-container">',
        '<div class="rsb-section__head"><span class="rsb-eyebrow">Product Overview</span>',
        f'<h2>{p["feature_section_title"]}</h2>',
        '<div class="rsb-divider rsb-divider--center"></div>',
        f'<p>{p["feature_section_intro"]}</p></div>',
        '<div class="rsb-split">',
        f'<div class="rsb-split__media"><div class="rsb-split__img" style="background-image:url(\'{img_url(p["split_img"])}\')"></div></div>',
        '<div class="rsb-split__body">',
        '<span class="rsb-split__eyebrow">How it works</span>',
        f'<h2>{p["split_title"]}</h2>',
        '<div class="rsb-divider"></div>',
        f"<p>{p['split_para']}</p>",
        f'<ul class="rsb-split__list">{split_list_html}</ul>',
        '<div class="rsb-split__actions"><a href="get-quote.html" class="rsb-btn rsb-btn--primary">Request a Quote</a><a href="products.html" class="rsb-btn rsb-btn--ghost-alt">Download Datasheet</a></div>',
        "</div></div></div></section>",
        # Spec table
        '<section class="rsb-section"><div class="rsb-container">',
        '<div class="rsb-section__head"><span class="rsb-eyebrow">Technical Specification</span>',
        f"<h2>Full specification for {p['breadcrumb_current'].replace('&amp;','&')}</h2>",
        '<div class="rsb-divider rsb-divider--center"></div>',
        "<p>Detailed specification covering insertion loss, panel construction, structural post spacing, corrosion class and transparent window options.</p></div>",
        '<div class="rsb-tablewrap">',
        f'<div class="rsb-table-head"><h3>{p["spec_title"]}</h3></div>',
        '<div class="rsb-table-body"><table class="rsb-table"><thead><tr><th>Property</th><th>Value</th></tr></thead>',
        f"<tbody>{spec_rows_html}</tbody></table></div>",
        "</div></div></section>",
        # Features
        '<section class="rsb-section rsb-section--gray"><div class="rsb-container">',
        '<div class="rsb-section__head"><span class="rsb-eyebrow">Why Yukings</span>',
        f'<h2>{p["feature_section_title"]}</h2>',
        '<div class="rsb-divider rsb-divider--center"></div>',
        f"<p>{p['feature_section_intro']}</p></div>",
        f'<div class="rsb-features">{features_html}</div>',
        "</div></section>",
        # Related products
        '<section class="rsb-section"><div class="rsb-container">',
        '<div class="rsb-section__head"><span class="rsb-eyebrow">Related Scenarios</span>',
        "<h2>Explore other noise barrier applications</h2>",
        '<div class="rsb-divider rsb-divider--center"></div>',
        "<p>Discover how Yukings designs different noise barriers for railways, city roads, bridges, industrial plants and residential communities.</p></div>",
        f'<div class="rsb-grid rsb-grid--3">{cards_html}</div>',
        "</div></section>",
        # FAQ
        '<section class="rsb-section rsb-section--gray"><div class="rsb-container">',
        '<div class="rsb-section__head"><span class="rsb-eyebrow">Frequently Asked Questions</span>',
        f"<h2>FAQ — {p['breadcrumb_current']}</h2>",
        '<div class="rsb-divider rsb-divider--center"></div>',
        "<p>Answers to the most common project questions about Yukings noise barriers, from acoustic performance to installation and certification.</p></div>",
        f'<div class="rsb-faq">{faq_html}</div>',
        "</div></section>",
        # CTA
        '<section class="rsb-cta"><div class="rsb-container"><div class="rsb-cta__inner">',
        '<span class="rsb-eyebrow">Ready to Take the Next Step?</span>',
        f"<h2>{p['cta_h2']}</h2>",
        f"<p>{p['cta_para']}</p>",
        '<div class="rsb-cta__actions"><a href="get-quote.html" class="rsb-btn rsb-btn--primary rsb-btn--lg">Get a Free Project Quote</a><a href="contact.html" class="rsb-btn rsb-btn--ghost rsb-btn--lg">Contact Our Engineers</a></div>',
        '<div class="rsb-cta__contacts">',
        '<div class="rsb-cta__contact"><i>&#9742;</i><div><strong>Tel</strong><span>+86-755-86366707</span></div></div>',
        '<div class="rsb-cta__contact"><i>&#9993;</i><div><strong>Email</strong><span>weilai04525@163.com</span></div></div>',
        '<div class="rsb-cta__contact"><i>&#9990;</i><div><strong>Sales (Miss Tang)</strong><span>+86 17727812004</span></div></div>',
        '<div class="rsb-cta__contact"><i>&#9990;</i><div><strong>Engineering (Mr. Yu)</strong><span>+86 13828819804</span></div></div>',
        "</div></div></div></section>",
        # Contact form
        '<section class="rsb-section rsb-section--gray"><div class="rsb-container"><div class="rsb-form"><h3>Get a tailored noise barrier quote</h3><p>Tell us about your project and we&#8217;ll get back to you within 24 hours.</p>',
        '<form onsubmit="return false;"><div class="rsb-form__grid">',
        '<div class="rsb-form__field"><label>Your name</label><input type="text"></div>',
        '<div class="rsb-form__field"><label>Company</label><input type="text"></div>',
        '<div class="rsb-form__field"><label>Email</label><input type="email"></div>',
        '<div class="rsb-form__field"><label>Phone</label><input type="tel"></div>',
        '<div class="rsb-form__field rsb-form__field--full"><label>Project type</label><input type="text" placeholder="e.g. highway, railway, bridge, industrial, residential"></div>',
        '<div class="rsb-form__field rsb-form__field--full"><label>Project details</label><textarea rows="5" placeholder="Project location, barrier length, target noise reduction, timeline..."></textarea></div>',
        '</div><button type="submit" class="rsb-btn rsb-btn--primary rsb-btn--lg rsb-form__submit">Send Project Inquiry</button></form>',
        "</div></div></section>",
        FOOTER_COOKIE,
        "</body></html>",
    ]

    return "\n".join(html_parts)


def main():
    for p in page_data():
        path = os.path.join(OUT, p["filename"])
        content = build_page(p)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Wrote {path} ({len(content.splitlines())} lines)")


if __name__ == "__main__":
    main()
